### ISSUE TITLE
Android release check update not work

### ISSUE THREAD

**Issue by gfoxlin** [crazecoder/flutter_pgyer#11]
Debug 运行可以检测更新
release 下运行 检测更新不执行回调 

flutter_pgyer: ^2.1.2+1

**Comment by gfoxlin** [comment]
W/System.err: java.lang.NoSuchMethodException: e.a.a.c.a.checkVersionUpdate / checkSoftwareUpdate

**Comment by hpp0hpp** [comment]
也不弹窗提醒更新

**Comment by lpfasd123** [comment]
> W/System.err: java.lang.NoSuchMethodException: e.a.a.c.a.checkVersionUpdate / checkSoftwareUpdate
解决了吗
同样问题

**Comment by crazecoder** [comment]
应用更新关注这个库[pgyer_updater](https://github.com/crazecoder/pgyer_updater)
