### ISSUE TITLE
这个是什么情况，求解

### ISSUE THREAD

**Issue by renamayu** [crazecoder/flutter_pgyer#5]
大佬，在安装的时候报错
Couldn't read file LocalFile: '/Users/test/.pub-cache/hosted/pub.dartlang.org/flutter_pgyer-1.0.1/android/src/main/kotlin/com/crazecoder/flutter/pgyer/FlutterPgyerPlugin.kt' even though it exists. Please verify that this file has read permission and try again.
exit code 1

**Comment by hqwlkj** [comment]
Couldn't read file LocalFile: '/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_pgyer-1.0.1/android/src/main/kotlin/com/crazecoder/flutter/pgyer/FlutterPgyerPlugin.kt' even though it exists. Please verify that this file has read permission and try again.


同样的问题

@renamayu  你处理了吗

**Comment by crazecoder** [comment]
github里的example有问题吗？

**Comment by renamayu** [comment]
我使用这个没成功过，总是遇到各种问题，干脆放弃了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "crazecoder"<notifications@github.com&gt;; 
发送时间: 2020年1月9日(星期四) 下午5:52
收件人: "crazecoder/flutter_pgyer"<flutter_pgyer@noreply.github.com&gt;; 
抄送: "喵"<myy326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [crazecoder/flutter_pgyer] 这个是什么情况，求解 (#5)




github里的example有问题吗？

**Comment by renamayu** [comment]
没有解决，已经放弃




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yanghc"<notifications@github.com&gt;; 
发送时间: 2020年1月7日(星期二) 中午11:52
收件人: "crazecoder/flutter_pgyer"<flutter_pgyer@noreply.github.com&gt;; 
抄送: "喵"<myy326@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [crazecoder/flutter_pgyer] 这个是什么情况，求解 (#5)




Couldn't read file LocalFile: '/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_pgyer-1.0.1/android/src/main/kotlin/com/crazecoder/flutter/pgyer/FlutterPgyerPlugin.kt' even though it exists. Please verify that this file has read permission and try again.
 
同样的问题
 
@renamayu  你处理了吗

**Comment by crazecoder** [comment]
好的，这个库现在也不推荐使用，现在也只有反馈和更新能用了，crash上报官方一直放手不管，推荐使用bugly

**Comment by pengjinlong** [comment]
有毒吧，安装就报错也不解决

**Comment by pengjinlong** [comment]
flutter_pgyer: 
    git:
      url: https://github.com/crazecoder/flutter_pgyer.git

用git的方式不会报错，亲测

**Comment by houko** [comment]
> flutter_pgyer:
> git:
> url: https://github.com/crazecoder/flutter_pgyer.git
> 
> 用git的方式不会报错，亲测

我试了是可以下载，也就是说最新的pub上的1.0.1不是github最新的代码呗  作者不管这个项目了吗？
